### ISSUE TITLE
讨论：成立飞桨社区开源发展委员会

### ISSUE THREAD

**Issue by jzhang533** [PaddlePaddle/community#608]
各位飞桨开源社区的成员，想跟大家在线上讨论一下，我们想要成立飞桨开源发展委员会的初步想法。
目前还是一个草稿阶段，当中的任何内容都欢迎大家回复发表意见。
BTW： 这个初步方案经过了百度内部的讨论，并获得了支持。

## 目的
* 为飞桨社区现在的关键事项进行决策。
* 加强飞桨社区的透明治理，让社区成员有更多的参与和社区认同。

## 名称
暂定的名字：飞桨社区开源发展委员会（PaddlePaddle OpenSource Development Committee），这个名字参考了：[CCF 开源发展委员会](https://www.ccf.org.cn/kyfzwyh/)。

## 职责范围
* 决策社区运营当中的关键事项，如：
  * 开源贡献证书上的文案。
  * 评选社区开源之星。
  * 制作什么样的社区礼品。
* 为社区未来的建设和发展提供建议
  * 举办什么样的社区活动
  * 完善和建设什么样的流程。（如：成为committer的流程、黑客松任务的参赛流程、PFCC例会是否需要改善、等）
* 仲裁社区中的突发事件
  * 违反Code of Conduct的情况的认定和处理。
  * 社区活动中，出现争议事件时的认定和仲裁。

## 人员构成
人数不宜过多，现在的方案是想：
* 由9个人组成：4个来自百度、5个来自社区。
考虑不设置委员会的主席和副主席，但是设置一名秘书的角色，来召集、主持会议等。秘书可以不是委员会成员。

## 任期
考虑任期为一年。到期之后需要重新产生新的委员会。

## 决策流程
* 对于重大决策（如需要仲裁类的事项），需要超过2/3的委员投票赞成，才可通过。
* 对于一般决策，采用默认通过的方式。（一名委员提出提议，另一名委员提出复议，其他人无人反对，即可通过。）

## 委员会产生方式
* 对于来自百度的委员
  * 在百度内部商议产生，但是需要在社区内，进行信任票的投票。
* 对于来自社区的委员
  * 需要从社区内选举产生，提前两周进行候选人征集，征集完成后，在社区内，进行投票产生。
* 候选人需要准备的材料
  * 准备一份简单的自我陈述的材料即可，材料里简介一下自己对开源和飞桨的认识，和对参与委员会的承诺，即可。
* 具体投票流程
  * 在某次PFCC的例会上，进行会上投票。
  * 参会人数达到20名以上，则可以形成有效投票人池。
  * 投票可选择：同意（+1）、反对（-1）、弃权（0）。
  * 过半数的人投同意票，则视为通过。
 
## 委员会例会
* 例行例会：每个季度召开一次。
  * Review这个季度的社区发展情况，这需要百度的委员提前准备。
  * 请社区委员，为未来社区发展提供建议。
* 按照特定事项来召开的例会
  * 提前准备材料，约好大家的时间，临时召开。

## 其他
* 委员的任期，名单，会议纪要，等等，等需要在community 仓库下留存。
* 委员可在任何时间辞任，辞任后，需重新产生新的委员。
* 任何委员如果连续缺席两次委员会的例会，则视为自动放弃委员身份。

**Comment by jingsongliujing** [comment]
我先发表一下我自己的看法哈
1.飞桨社区开源发展委员会成员是否只包含PFCC成员，不包括飞桨社区其他成员。
2.除了线上会议以外是否还有其他活动
3.除了委员会成员和委员，是否还有其他角色
4.委员会成员的一个扩充需要什么门槛能进入，是否是pfcc=委员会成员

**Comment by jzhang533** [comment]
> 1.飞桨社区开源发展委员会成员是否只包含PFCC成员，不包括飞桨社区其他成员。
现在的想法是不局限于PFCC的成员，只要是飞桨社区的成员就可以的，在成立之前我们可以请大家推荐或者自荐。

> 2.除了线上会议以外是否还有其他活动
可以有其他的活动的，但现阶段最主要的出发点，是设置一种机制，通过委员会，能对社区的关键事项进行讨论和决策。

> 3.除了委员会成员和委员，是否还有其他角色
一般这样的委员会，是设置有chair, vice chair这样的角色的。现在的草稿里没有设置这两个觉得。
我想我们可以深入讨论，不知道你有没有什么好的提议。

> 4.委员会成员的一个扩充需要什么门槛能进入，是否是pfcc=委员会成员
现在的想法是设置9名委员，也许运转起来之后，可以看看是否有必要增设委员。
我现在是想不要有特别的门槛。但是期望是对飞桨开源有热情，在社区内已经积累了一定的影响力，并且承诺投入时间精力来参与的社区成员会是比较合适的候选人。

**Comment by jzhang533** [comment]
我们也从其他渠道收集到了反馈意见，此issue 将关闭。
终版请参看： https://github.com/PaddlePaddle/community/tree/master/pposdwg
