### ISSUE TITLE
WAVE SUMMIT+2023下半年飞桨开源之星评选-信息征集

### ISSUE THREAD

**Issue by Ligoml** [PaddlePaddle/community#765]
大家好~很高兴告诉大家，飞桨开源社区 **2023下半年开源之星** 评选正式启动啦（撒花 🎉

**🌟飞桨开源之星🌟** 是飞桨开源社区开发者的最高荣誉，用于表彰一段时间内为飞桨开源项目（含 PaddlePaddle 下的所有开源项目）做出突出开源代码贡献的社区开发者，每年评选两期，每期 10 人，在百度 WAVE SUMMIT 开发者大会上进行颁奖，并在开源社区公示。往期开源之星情况可以戳这里 ➡️ [飞桨开源之星](https://github.com/PaddlePaddle/community/blob/master/contributors/certificate-inspection.md#%E9%A3%9E%E6%A1%A8%E5%BC%80%E6%BA%90%E4%B9%8B%E6%98%9F)。感兴趣的话快来提交评选信息吧~~

ps. 本期开源之星将由 [飞桨社区开源发展工作组](https://github.com/PaddlePaddle/community/tree/master/pposdwg) 完成评定，全过程公开透明，欢迎监督！

pps. PaddlePaddle Hackathon 5th 活动进行中，根据活动规则设计，在第五期飞桨黑客松活动中 **获取 🌟 数排名前 3 的开发者当选飞桨开源之星**，该结果会在12月22日黑客松结果公示中同步更新~

## 报名方式

参选范围：非百度任职的飞桨开源项目贡献者
贡献时间：2023年6月1日-2023年11月30日

本期开源之星候选人采取自荐的方式，有意向参与评选的开发者请参考如下格式回复本 issue，如果有你支持的开发者，**欢迎通过回复表情点赞 👍 的方式提高 ta 的人气呀~**

```
### Github ID：[xxx](https://github.com/xxx)
(个人介绍)

### PR 贡献（必填）

- PR 提交次数：xx / [查询链接](https://github.com/search?q=author%3ALigoml+org%3APaddlePaddle+is%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests) （注意替换 author 值）
- 代表性 PR 展示：

### ISSUE 贡献（必填）

- ISSUE 提交次数：xx / [查询链接](https://github.com/search?q=author%3ALigoml+org%3APaddlePaddle+is%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues) （注意替换 author 值）
- 代表性 ISSUE 展示：

### 评论贡献（必填）

- 评论 ISSUE 次数：xx / [查询链接](https://github.com/search?q=commenter%3ALigoml+org%3APaddlePaddle+type%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues) （注意替换 author 值）
- 评论 PR 次数：xx / [查询链接](https://github.com/search?q=commenter%3ALigoml+org%3APaddlePaddle+type%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests) （注意替换 author 值）

### 代码审查贡献（必填）

- 评审次数：xx / [查询链接](https://github.com/search?q=type%3Apr++reviewed-by%3ALigoml++org%3APaddlePaddle+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)（注意替换 author 值）
- 代码审查贡献简述：（如主要参与哪些方面的代码审查，review 多少人的 pr 等）

### 生态贡献（加分项）

- 开源布道：如发布关于开源的专著、文章、公众号等，或是受邀参加技术峰会、开发者大会等，或是在相关会议、活动上推广开源文化等（对活动形式和参与次数进行描述）
- 社区活动：组织或参与社区SIG会议、技术交流、成员单位meetup、开源校源行等（对活动形式和参与次数进行描述）

### 自荐理由 （必填）

评审结果不仅是比较每项指标数量上的差异，将结合每位开发者贡献产生的影响力予以客观公正的评价。申请人可对每项提供数据的指标，进行影响力、活跃度、代码质量、项目效果等方面进行补充描述，字数不限。
```

## 报名截止时间

**2023年12月11日**，截止报名后此 issue 会关闭，启动 **飞桨社区开源发展工作组** 评审。

## 彩蛋 🍻 🍻 🍻 

如果你想围观看看，飞桨框架的代码贡献情况，可以考虑使用这个命令： `git shortlog -n --since="2023-7-1"`，如果你还想继续深挖看看的话，可以考虑用这个代码仓库： https://github.com/PFCCLab/release-notes-drafter

**Comment by Liyulingyue** [comment]
### Github ID：[xxx](https://github.com/xxx)
(个人介绍)

### PR 贡献

- PR 提交次数：xx / [查询链接](https://github.com/search?q=author%3ALigoml+org%3APaddlePaddle+is%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests) （注意替换 author 值）
- 代表性 PR 展示：

### ISSUE 贡献

- ISSUE 提交次数：xx / [查询链接](https://github.com/search?q=author%3ALigoml+org%3APaddlePaddle+is%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues) （注意替换 author 值）
- 代表性 ISSUE 展示：

### 评论贡献

- 评论 ISSUE 次数：xx / [查询链接](https://github.com/search?q=commenter%3ALigoml+org%3APaddlePaddle+type%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues) （注意替换 author 值）
- 评论 PR 次数：xx / [查询链接](https://github.com/search?q=commenter%3ALigoml+org%3APaddlePaddle+type%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests) （注意替换 author 值）

### 代码审查贡献

- 评审次数：xx / [查询链接](https://github.com/search?q=type%3Apr++reviewed-by%3ALigoml++org%3APaddlePaddle+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)（注意替换 author 值）
- 代码审查贡献简述：（如主要参与哪些方面的代码审查，review 多少人的 pr 等）

**Comment by zrr1999** [comment]
### Github ID：[zrr1999](https://github.com/zrr1999)

### PR 贡献

- PR 提交次数：41 / [查询链接](https://github.com/search?q=author%3Azrr1999+org%3APaddlePaddle+is%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests) 
- 代表性 PR 展示：
    - https://github.com/PaddlePaddle/Paddle/pull/57443
    - https://github.com/PaddlePaddle/PaddleSOT/pull/369
    - https://github.com/PaddlePaddle/PaddleSOT/pull/371
    - https://github.com/PaddlePaddle/Paddle/pull/59041
    - https://github.com/PaddlePaddle/Paddle/pull/57444

### ISSUE 贡献

- ISSUE 提交次数：4 / [查询链接](https://github.com/search?q=author%3Azrr1999+org%3APaddlePaddle+is%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues) 
- 代表性 ISSUE 展示：
    - https://github.com/PaddlePaddle/PaddleSOT/issues/142
    - https://github.com/PaddlePaddle/PaddleSOT/issues/169
    - https://github.com/PaddlePaddle/PaddleSOT/issues/360

### 评论贡献

- 评论 ISSUE 次数：7 / [查询链接](https://github.com/search?q=commenter%3Azrr1999+org%3APaddlePaddle+type%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues) 
- 评论 PR 次数：91 / [查询链接](https://github.com/search?q=commenter%3Azrr1999+org%3APaddlePaddle+type%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests) 

### 代码审查贡献

- 评审次数：88 / [查询链接](https://github.com/search?q=type%3Apr++reviewed-by%3Azrr1999++org%3APaddlePaddle+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)
- 代码审查贡献简述：主要参与 `PaddleSOT` 和代码风格相关的 PR。

**Comment by gouzil** [comment]
### Github ID：[gouzil](https://github.com/gouzil)

喵喵喵，喵，喵喵？汪！喵o(_￣3￣)o ！

### PR 贡献

- PR 提交次数：159 / [查询链接](https://github.com/search?q=author%3Agouzil+org%3APaddlePaddle+is%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)
- 代表性 PR 展示：
  - https://github.com/PaddlePaddle/Paddle/issues/58967
  - https://github.com/PaddlePaddle/Paddle/issues/58966


### ISSUE 贡献

- ISSUE 提交次数：7 / [查询链接](https://github.com/search?q=author%3Agouzil+org%3APaddlePaddle+is%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues)
- 代表性 ISSUE 展示：
  - https://github.com/PaddlePaddle/Paddle/issues/58356
  - https://github.com/PaddlePaddle/Paddle/issues/57367

### 评论贡献

- 评论 ISSUE 次数：13 / [查询链接](https://github.com/search?q=commenter%3Agouzil+org%3APaddlePaddle+type%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues)
- 评论 PR 次数：161 / [查询链接](https://github.com/search?q=commenter%3Agouzil+org%3APaddlePaddle+type%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)

### 代码审查贡献

- 评审次数：106 / [查询链接](https://github.com/search?q=type%3Apr++reviewed-by%3Agouzil++org%3APaddlePaddle+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)
- 代码审查贡献简述：
  - 主要参与 PaddleSOT 和代码风格相关的 PR


### 生态贡献

- 社区活动：上海开发者嘉年华

### 自荐理由

我也不知道啥理由，但是参与开源的时间学习到了很多，也帮助 paddle 解决了许多问题，认识了很多有趣的开发者和卷王们。

**Comment by enkilee** [comment]
### Github ID：[enkilee](https://github.com/enkilee)
专业摸鱼

### PR 贡献

- PR 提交次数：88
- 代表性 PR 展示：
https://github.com/PaddlePaddle/Paddle/pull/59091 增加PIR相关代码和单测
https://github.com/PaddlePaddle/Paddle/pull/58848 修正Docs存在的问题
https://github.com/PaddlePaddle/PaddleScience/pull/607 基于hydra的案例改造计划
https://github.com/PaddlePaddle/Paddle/pull/58285 引入clang-tidy
https://github.com/PaddlePaddle/Paddle/pull/57277 迁移API到PIR
https://github.com/PaddlePaddle/Paddle/pull/56761 API易用性提升

### 评论贡献（必填）

- 评论 ISSUE 次数：10 
- 评论 PR 次数：56 

### 代码审查贡献（必填）

- 评审次数：38 
- 代码审查贡献简述：Docathon、xdoctest、CodeStyle、NewIR等

### 自荐理由 （必填）
相比上述各位大佬，实在是找不到什么充分的理由，就努力在新手村打怪升级，争取赶上各位大佬的级别和技能。

**Comment by MarioLulab** [comment]
### Github ID：[MarioLulab](https://github.com/MarioLulab)

写写代码，看看世界

### PR 贡献

- PR 提交次数：[33](https://github.com/search?q=author%3AMarioLulab+org%3APaddlePaddle+is%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)
- 代表性 PR 展示：
  - PyLayer 支持动转静，添加 PyLayer Op：https://github.com/PaddlePaddle/Paddle/pull/56108
  - PyLayer 支持动转静，动转静感知并转写 PyLayer ：https://github.com/PaddlePaddle/Paddle/pull/56531
  - 组网 API PIR 迁移：https://github.com/PaddlePaddle/Paddle/pull/58453
  - 组网 API PIR 迁移：https://github.com/PaddlePaddle/Paddle/pull/59419
  - PIR 自动代码生成由 make 阶段移至 cmake 阶段：https://github.com/PaddlePaddle/Paddle/pull/59129
  - 增添 PIR 模式中的执行器输入变量检查：https://github.com/PaddlePaddle/Paddle/pull/58984
  - eager properties 适配分布式 tensor ：https://github.com/PaddlePaddle/Paddle/pull/58746
  - embedding_grad 支持自动并行：https://github.com/PaddlePaddle/Paddle/pull/58928

### ISSUE 贡献

- ISSUE 提交次数：[4](https://github.com/search?q=author%3AMarioLulab+org%3APaddlePaddle+is%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues)
- 代表性 ISSUE 展示：
  * PIR Python API 适配升级任务发布、维护和推进：https://github.com/PaddlePaddle/Paddle/issues/58067
  * 组网 API PIR 适配升级任务 bug 修复手册：https://github.com/PaddlePaddle/Paddle/issues/58259

### 评论贡献

- 评论 ISSUE 次数：[4](https://github.com/search?q=commenter%3AMarioLulab+org%3APaddlePaddle+type%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues)
- 评论 PR 次数：[75](https://github.com/search?q=commenter%3AMarioLulab+org%3APaddlePaddle+type%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)

### 代码审查贡献

- 评审次数：[71](https://github.com/search?q=type%3Apr++reviewed-by%3AMarioLulab++org%3APaddlePaddle+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)
- 代码审查贡献简述：主要 review `组网 API PIR 升级适配任务` 的 PR，为开发者 fix bugs，并检查单测覆盖率，反馈问题给 paddle 内部研发，有序推动 PIR 在 Python 组网 API 侧的适配升级

### 生态贡献

- 社区活动：参加上海开发者嘉年华，近距离观摩各位研发和 PFCC 大佬；担任飞桨护航计划集训营助教

### 自荐理由

很惭愧，就做了一点微小的工作，谢谢大家！

**Comment by qiuwenbogdut** [comment]
### Github ID：[qiuwenbogdut](https://github.com/qiuwenbogdut)
一名想回家养螃蟹的打工人

### PR 贡献（必填）

- PR 提交次数：7 / [查询链接](https://github.com/search?q=author%3Aqiuwenbogdut+org%3APaddlePaddle+is%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)
- 代表性 PR 展示：
	- https://github.com/PaddlePaddle/community/pull/535
	- https://github.com/PaddlePaddle/Paddle/pull/54838
	- https://github.com/PaddlePaddle/Paddle/pull/55627
    -   https://github.com/PaddlePaddle/community/pull/600
    - https://github.com/PaddlePaddle/Paddle/pull/56837

### ISSUE 贡献（必填）

- ISSUE 提交次数：2 / [查询链接](https://github.com/search?q=author%3Aqiuwenbogdut+org%3APaddlePaddle+is%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues)
- 代表性 ISSUE 展示：
	- https://github.com/PaddlePaddle/Paddle/issues/56479
	- https://github.com/PaddlePaddle/Paddle/issues/54347

### 评论贡献（必填）

- 评论 ISSUE 次数：3 / [查询链接](https://github.com/search?q=commenter%3Aqiuwenbogdut+org%3APaddlePaddle+type%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues)
- 评论 PR 次数：4 / [查询链接](https://github.com/search?q=commenter%3Aqiuwenbogdut+org%3APaddlePaddle+type%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests) 

### 代码审查贡献（必填）

- 评审次数：4 / [查询链接](https://github.com/search?q=type%3Apr++reviewed-by%3Aqiuwenbogdut++org%3APaddlePaddle+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)
- 代码审查贡献简述：主要是参与关于反向图可视化相关的代码review

### 生态贡献（加分项）
- 社区活动：参与PFCC周会,并进行了一次关于反向图可视化的技术分享

### 自荐理由 （必填）
最近半年来持续参与paddle的开源活动 针对飞桨动态图的反向图调试能力存在不足问题。在[欢哥](https://github.com/wanghuancoder)的指导下和[Tomoko-hjf](https://github.com/Tomoko-hjf)协作开发了一个反向图可视化工具:

- [为飞桨动态图框架添加反向节点在 Python 端的访问机制](https://github.com/PaddlePaddle/Paddle/issues/53172#paddlepaddle07),
- 为飞桨框架扩展反向图可视化能力,开发了反向图可视化工具[paddleviz](https://github.com/PFCCLab/paddleviz/)
- [扩展 paddleviz 的能力, 将反向图边（Tensor）的调试信息，如Tensor name、shape、dtype、place可视化出来, 进一步提升反向图的调试能力](https://github.com/PaddlePaddle/Paddle/issues/55663#paddlepaddle08).

开发的工具成效:
- [paddleviz](https://github.com/PFCCLab/paddleviz/)能大幅提升RD分析疑难问题的效率。
- Torch也有对应的调试工具torchviz，但torchviz只能展示拓扑结构，信息不够充分。而[paddleviz](https://github.com/PFCCLab/paddleviz/)在展示拓扑结构基础上，还展示了节点间传递Tensor的基本信息，更有利于问题分析。
- 基于该项目参与第六届中国软件开源创新大赛 获得了二等奖

今年是自己参与开源的元年 能够在一开始就能够进入到飞桨社区和一群有趣又优秀的小伙伴一起开发真是太有意思了, 期待我们的社区能够越来越红火.

**Comment by ccsuzzh** [comment]
### Github ID：[ccsuzzh](https://github.com/ccsuzzh)
Hello, HappyOpenSource!

### PR 贡献

- PR 提交次数：30 / [查询链接](https://github.com/search?q=author%3Accsuzzh+org%3APaddlePaddle+is%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)
- 代表性 PR 展示：
https://github.com/PaddlePaddle/Paddle/pull/58781
https://github.com/PaddlePaddle/Paddle/pull/57412
https://github.com/PaddlePaddle/Paddle/pull/56744
https://github.com/PaddlePaddle/Paddle/pull/55432
https://github.com/PaddlePaddle/Paddle/pull/54628
https://github.com/PaddlePaddle/PaddleCustomDevice/pull/605

### ISSUE 贡献

- ISSUE 提交次数：0 / [查询链接](https://github.com/search?q=author%3Accsuzzh+org%3APaddlePaddle+is%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues)

### 评论贡献

- 评论 ISSUE 次数：12 / [查询链接](https://github.com/search?q=commenter%3Accsuzzh+org%3APaddlePaddle+type%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues)
- 评论 PR 次数：17 / [查询链接](https://github.com/search?q=commenter%3Accsuzzh+org%3APaddlePaddle+type%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)

### 代码审查贡献

- 评审次数：8 / [查询链接](https://github.com/search?q=type%3Apr++reviewed-by%3Accsuzzh++org%3APaddlePaddle+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)

### 生态贡献

- 社区活动：上海开发者嘉年华

### 自荐理由

作为各位大佬的对照组，进一步凸显大佬们与普通人的差距。
在参与开源社区的一年中，真正学习到很多新知识，也见识到了很多新技术，社区一定会发展地越来越好！

**Comment by AndSonder** [comment]
### Github ID：[AndSonder](https://github.com/andsonder)



### PR 贡献（必填）

- PR 提交次数：33 / [查询链接](https://github.com/search?q=author%3AAndSonder+org%3APaddlePaddle+is%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests) 
- 代表性 PR 展示：
- https://github.com/PaddlePaddle/Paddle/pull/55389
- https://github.com/PaddlePaddle/Paddle/pull/55650
- https://github.com/PaddlePaddle/Paddle/pull/56185
- https://github.com/PaddlePaddle/Paddle/pull/56696
- https://github.com/PaddlePaddle/Paddle/pull/57616
- https://github.com/PaddlePaddle/Paddle/pull/58313

### ISSUE 贡献（必填）

- ISSUE 提交次数：3 / [查询链接](https://github.com/search?q=author%3AAndSonder+org%3APaddlePaddle+is%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues) 
- 代表性 ISSUE 展示：
- https://github.com/PaddlePaddle/Paddle/issues/55299
- https://github.com/PaddlePaddle/Paddle/issues/55907

### 评论贡献（必填）

- 评论 ISSUE 次数：8 / [查询链接](https://github.com/search?q=commenter%3AAndSonder+org%3APaddlePaddle+type%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues) 
- 评论 PR 次数：20 / [查询链接](https://github.com/search?q=commenter%3AAndSonder+org%3APaddlePaddle+type%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests) 

### 代码审查贡献（必填）

- 评审次数：10 / [查询链接](https://github.com/search?q=type%3Apr++reviewed-by%3AAndSonder++org%3APaddlePaddle+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)


### 生态贡献（加分项）

- 社区活动：上海开发者嘉年华，成都meetup，主持PFCC会议一次，在中国软件开源创新大赛介绍会上帮忙介绍赛题

### 自荐理由 （必填）

从第一次框架护航开始持续参加飞桨开源项目，在[锐彪哥](https://github.com/From00)的指导下着手推进了飞桨静态选Kernel、静态图预分析性能优化和飞桨静态图流水并行分析工具的建设，后续也会继续参与大模型场景下静态图性能分析与优化的课题。非常开心能为Paddle和Paddle社区做出贡献，期待未来能够与大家一起多多给Paddle提PR，共同推动Paddle的发展。

**Comment by Difers** [comment]
### Github ID：[Difers](https://github.com/Difers)
(个人介绍)

### PR 贡献（必填）

- PR 提交次数：28 / [查询链接](https://github.com/search?q=author%3ADifers+org%3APaddlePaddle+is%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests) （注意替换 author 值）
- 代表性 PR 展示：
https://github.com/PaddlePaddle/Paddle/pull/56576
https://github.com/PaddlePaddle/Paddle/pull/55345
https://github.com/PaddlePaddle/Paddle/pull/55522
https://github.com/PaddlePaddle/Paddle/pull/58269
https://github.com/PaddlePaddle/VisualDL/pull/1263
### ISSUE 贡献（必填）

- ISSUE 提交次数：1 / [查询链接](https://github.com/search?q=author%3ADifers+org%3APaddlePaddle+is%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues) （注意替换 author 值）
- 代表性 ISSUE 展示：

### 评论贡献（必填）

- 评论 ISSUE 次数：9 / [查询链接](https://github.com/search?q=commenter%3ADifers+org%3APaddlePaddle+type%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues) （注意替换 author 值）
- 评论 PR 次数：15 / [查询链接](https://github.com/search?q=commenter%3ADifers+org%3APaddlePaddle+type%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests) （注意替换 author 值）

### 代码审查贡献（必填）

- 评审次数：10 / [查询链接](https://github.com/search?q=type%3Apr++reviewed-by%3ADifers++org%3APaddlePaddle+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)（注意替换 author 值）

### 生态贡献（加分项）
- 社区活动：主持PFCC会议一次

### 自荐理由 （必填）

从git都不用的小白，都现在能够做一点力所能及的贡献，这一年感谢飞桨社区的大家带我进行了一步步的打怪升级~
期待未来能够与大家继续成长，相信社区也将会变得刚好更热闹(๑•̀ㅂ•́)و✧

**Comment by megemini** [comment]
### Github ID：[megemini](https://github.com/megemini)

### PR 贡献（必填）
* PR 提交次数：42 / [查询链接](https://github.com/search?q=author%3Amegemini+org%3APaddlePaddle+is%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)
* 代表性 PR 展示：
* [【Hackathon 5th No.33】为 Paddle 新增 atleast_1d / atleast_2d / atleast_3d API -part #58323](https://github.com/PaddlePaddle/Paddle/pull/58323)
* [【Hackathon 5th No.38】为 Paddle 新增 FractionalMaxPool2d / FractionalMaxPool3d API #698](https://github.com/PaddlePaddle/community/pull/698)
* [[Add] Paddle 代码 CI 中引入 xdoctest 检查 #55295](https://github.com/PaddlePaddle/Paddle/pull/55295)
* [[Change] 更新文档《开发 API Python 端》与《API 文档书写规范》 #6096](https://github.com/PaddlePaddle/docs/pull/6096)

### ISSUE 贡献（必填）
* ISSUE 提交次数：3 / [查询链接](https://github.com/search?q=author%3Amegemini+org%3APaddlePaddle+is%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues)
* 代表性 ISSUE 展示：
* [赛题五：将 xdoctest 引入到飞桨框架工作流中 Tracking Issue #54705](https://github.com/PaddlePaddle/Paddle/issues/54705)
* [修改目前 Paddle docs 中仍使用 code-block 的示例代码为 COPY-FROM #5957](https://github.com/PaddlePaddle/docs/issues/5957)
* [[xdoctest] 分批次修改已有代码的示例 #55629](https://github.com/PaddlePaddle/Paddle/issues/55629)

### 评论贡献（必填）
* 评论 ISSUE 次数：1 / [查询链接](https://github.com/search?q=commenter%3Amegemini+org%3APaddlePaddle+type%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues)
* 评论 PR 次数：102 / [查询链接](https://github.com/search?q=commenter%3Amegemini+org%3APaddlePaddle+type%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)

### 代码审查贡献（必填）
* 评审次数：87 / [查询链接](https://github.com/search?q=type%3Apr++reviewed-by%3Amegemini++org%3APaddlePaddle+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)

### 生态贡献（加分项）
* PFCC 分享一次

### 自荐理由 （必填）
社区里的大佬太多，重拾c++，向大佬看齐！希望追赶上十年前的自己 ～ （Python 是最好的编程语言 🫡）

**Comment by DrRyanHuang** [comment]
### Github ID：[drryanhuang](https://github.com/drryanhuang)

飞桨开源社区气氛组成员

### PR 贡献（必填）

- PR 提交次数：39 / [查询链接](https://github.com/search?q=author%3Adrryanhuang+org%3APaddlePaddle+is%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests) 
- 代表性 PR 展示：
https://github.com/PaddlePaddle/Paddle/pull/56550
https://github.com/PaddlePaddle/community/pull/627
https://github.com/PaddlePaddle/Paddle/pull/58517
https://github.com/PaddlePaddle/Paddle/pull/58620
https://github.com/PaddlePaddle/Paddle/pull/58688
https://github.com/PaddlePaddle/PaddleScience/pull/627
### ISSUE 贡献（必填）

- ISSUE 提交次数：2 / [查询链接](https://github.com/search?q=author%3ADrRyanHuang+org%3APaddlePaddle+is%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues) （注意替换 author 值）
- 代表性 ISSUE 展示：
https://github.com/PaddlePaddle/Paddle/issues/56880
https://github.com/PaddlePaddle/Paddle/issues/56879
### 评论贡献（必填）

- 评论 ISSUE 次数：2 / [查询链接](https://github.com/search?q=commenter%3ADrRyanHuang+org%3APaddlePaddle+type%3Aissue+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=issues)
- 评论 PR 次数：27 / [查询链接](https://github.com/search?q=commenter%3Adrryanhuang+org%3APaddlePaddle+type%3Apr+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)

### 代码审查贡献（必填）

- 评审次数：8 / [查询链接](https://github.com/search?q=type%3Apr++reviewed-by%3Adrryanhuang++org%3APaddlePaddle+created%3A%3E2023-06-01+updated%3A%3C2023-11-30&type=pullrequests)

### 生态贡献（加分项）

社区活动：上海开发者嘉年华


### 自荐理由 （必填）

<details>

<summary> <del>这里空白太小，写不下🐶</del> </summary>

我想，开源精神在于想法，并实现出来，公开出来，邀请更多的人参与进来，和身边的人一起成长，并从中获得乐趣，而所做的一切皆是因为热爱。

和大家一样，最初，我也只是一个胆小且羞涩的社区开发者，提PR时，总是小心翼翼，十分谨慎，生怕误操作。当时也只是敢简单地修修文档，修修边边角角(现在也是😂)，比如我github上前四个merged的pr：

- https://github.com/PaddlePaddle/PaddleSlim/pull/209
- https://github.com/PaddlePaddle/models/pull/4828
- https://github.com/PaddlePaddle/docs/pull/3013
- https://github.com/PaddlePaddle/Paddle-Lite/pull/5891



遥想起我的第一个[正式PR](https://github.com/PaddlePaddle/Paddle/pull/47908), [涛姐](https://github.com/luotao1)和[jerrywgz](https://github.com/jerrywgz)引导我一步步改单测改API, 直到最后被merge. 我才逐渐了解到一些飞桨框架的开发流程，一个API对应一个单测，以及要做代码风格检查之类的. 之后也尝试做了一些快乐开源的其他任务，比如[TensorRT算子](https://github.com/PaddlePaddle/Paddle/pull/49113), [PHI算子库解耦](https://github.com/PaddlePaddle/Paddle/pull/49668), [飞桨 API 动静行为统一](https://github.com/PaddlePaddle/Paddle/issues/48612)和[PIR API 推全升级](https://github.com/PaddlePaddle/Paddle/pull/58675)等任务，认识了好多开源社区的小伙伴和研发大佬. 感谢动转静的小伙伴([杰哥](https://github.com/Aurelius84), [震哥](https://github.com/0x45f), [日升](https://github.com/YuanRisheng), [永康](https://github.com/kangguangli)和[喵喵](https://github.com/SigureMo))的悉心指导，感谢我的同门[陆琦大佬](https://github.com/MarioLulab)和[川宝](https://github.com/gouzil)的鼎力相助. 

有时候，提PR不能一次做到最好，比如我之前的[#49628](https://github.com/PaddlePaddle/Paddle/pull/49628) 😂，喵喵后来重新完善了一下，删除了一些冗余代码[#58302](https://github.com/PaddlePaddle/Paddle/pull/58302)，所以，在社区提PR就大胆地去尝试吧，~反正有研发会帮我们修~


<img alt="Xiao" src="https://github.com/PaddlePaddle/community/assets/44900829/84c86133-669a-4567-b6d4-ab27b9ce9ecc" width="50%"> </img>

感谢所有让我们受益匪浅的领路人，是你们引导着我们成长和前行。因为有了你们的点拨、教导和支持，才能让我们这些新人不断变成长，变得更好。

和开源社区的家人们熟悉起来后，也开始活跃起来，提PR，讲究一个极致的简约风格，主打的就是一个放空大脑，让双手自己操作，只要情感到了，单测自己就会通过😉😉😉，快乐开源，是真的快乐🥳🥳🥳


我也一直在尝试研读飞桨PIR和CINN部分的源码，让自己的Python代码足够Pythonic，并学习一些现代C++的用法，力求达到优雅、明确、简单的目标。在开源社区成长了很多，要一直努力学习，和开源社区的家人们多交流，才能为社区做更多的贡献。祝大家快乐开源，在社区玩得开心！

</details>
