### ISSUE TITLE
【社区开源发展工作组提案】第六期飞桨黑客松活动设立社区监督小组

### ISSUE THREAD

**Issue by Ligoml** [PaddlePaddle/community#804]
PaddlePaddle Hackathon飞桨黑客马拉松目前已顺利完成5期活动，为繁荣飞桨及生态伙伴开源项目做出了巨大的贡献，往期黑客松详情可见：
- https://github.com/PaddlePaddle/Paddle/issues/35940
- https://github.com/PaddlePaddle/Paddle/issues/40234
- https://github.com/PaddlePaddle/Paddle/issues/43938
- https://github.com/PaddlePaddle/Paddle/issues/51281
- https://github.com/PaddlePaddle/Paddle/issues/57262
- https://github.com/PaddlePaddle/Paddle/issues/57264
- https://github.com/PaddlePaddle/Paddle/issues/57585

在第五期活动中，社区开发者为我们带来了许多惊喜，@Tomoko-hjf 开发了黑客松小助手，自动统计 PR 提交信息并更新到榜单，解放了非常多的运营人力，@MarioLulab 搭建了开源项目 https://github.com/PFCCLab/Camp ，构建更加开源开放的 Code Camp 模式，得到了社区和飞桨产研团队的一致认可。

第六期飞桨黑客松筹备工作正在进行中，将由大家的老朋友 @sunzhongkai588 整体负责，在此我发起一个议题，为第六期飞桨黑客松活动设立社区监督小组，~~push 孙师傅干活~~，为飞桨社区最大的开源活动更加规范透明，也为有更多有活力有想法的社区开发者加入飞桨开源社区建设中来👀

**Comment by GreatV** [comment]
社区监督小组的作用是什么

**Comment by Zheng-Bicheng** [comment]
> 我现在的想法是以下几点，大家可以讨论和补充：
> 
> 1. 【监督孙师傅干活】重要时间节点的成果验收，比如任务发布（验收issue榜单和描述是否清晰）、直播课（review内容是否合理，能否指导开发）、中期大会（参与内容筹备和讨论，或者讨论后不需要中期大会也可以不开）、结果公示（任务是否如期完成，锁定的任务是否按照约定完成）
> 2. 【给孙师傅提需求】类似黑客松小助手之类的可以提升黑客松活动运营效率的小工具，黑客松中可以加入的新玩法新任务（如第五期数星星🌟，前三当选开源之星），etc

我先替孙师傅谢谢梦师傅了，哈哈哈哈哈哈哈哈哈哈哈

**Comment by jzhang533** [comment]
Resolution：飞桨社区开源发展工作组在第六期黑客松活动中承担社区监督小组的职责。
