### ISSUE TITLE
【社区开源发展工作组提案】更新PFCC的名称

### ISSUE THREAD

**Issue by jzhang533** [PaddlePaddle/community#805]
我想提议一下，给PFCC改个名字， 从Paddle Framework Contributor Club 更新成能体现出是所有给飞桨的开源项目做贡献的 Contributors 的一个虚拟组织。

目前的候选名称：
- Paddle Future Contributor Club (PFCC)，这个名称不需要更新简称。但是，可能不那么恰当。（Draft PR: #803 ) by @jzhang533 
- PaddlePaddle Contributor Club (PPCC). by @GreatV

**Comment by Zheng-Bicheng** [comment]
Paddle Community Contributors Alliance (PCCA) Paddle社区贡献者联盟

**Comment by jzhang533** [comment]
> Paddle Community Contributors Alliance (PCCA) Paddle社区贡献者联盟
Paddle Community Contributors Club， 还叫 Club，是不是也行？ Alliance 这个词，多用在公司之间的联盟上。

**Comment by Zheng-Bicheng** [comment]
> > Paddle Community Contributors Club， 还叫 Club，是不是也行？ Alliance 这个词，多用在公司之间的联盟上。

最开始是这么取的，但是缩写成PCCC感觉有点抽象，哈哈哈哈哈

**Comment by jinyouzhi** [comment]
我来脑暴几个F词 😇 
Frontier / Forerunner / Fellow 取先锋、前沿之意
Friends / Folks “家人们”
Fundamental / Foundation 取基础设施之意

**Comment by jzhang533** [comment]
Resolution: 保持PFCC的名称不变，但在介绍页面澄清，是所有给飞桨的开源项目做贡献的 Contributors 的一个虚拟组织。
